# Generated by Django 4.2.7 on 2026-01-01 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0011_tenantaddress'),
        ('students', '0004_alter_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False indicates the record has been soft deleted', verbose_name='Active Status')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('certificate_type', models.CharField(choices=[('MIGRATION', 'Migration Certificate'), ('TRANSCRIPT', 'Transcript'), ('CHARACTER', 'Character Certificate'), ('TRANSFER', 'Transfer Certificate (TC)'), ('BONAFIDE', 'Bonafide Certificate'), ('SLC', 'School Leaving Certificate')], max_length=20, verbose_name='Certificate Type')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Certificate Number')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date')),
                ('content', models.TextField(blank=True, help_text='Additional details or manual content override', verbose_name='Content/Remarks')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student', verbose_name='Student')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date', '-created_at'],
                'permissions': [('issue_certificate', 'Can issue certificates'), ('print_certificate', 'Can print certificates')],
            },
        ),
    ]
