# Generated by Django 4.2.7 on 2025-12-29 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_tenantconfiguration_square_logo'),
        ('finance', '0008_alter_bankaccount_as_of_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Universal ID')),
                ('data_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Data Integrity Signature')),
                ('encryption_version', models.CharField(default='v1', editable=False, max_length=10, verbose_name='Encryption Scheme Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Modification Timestamp')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Timestamp')),
                ('deletion_reason', models.TextField(blank=True, help_text='Mandatory for compliance: Reason for record deletion', null=True, verbose_name='Deletion Justification')),
                ('deletion_category', models.CharField(blank=True, choices=[('USER_REQUEST', 'User Request'), ('ADMIN_ACTION', 'Administrative Action'), ('SYSTEM_CLEANUP', 'System Cleanup'), ('COMPLIANCE', 'Compliance Requirement'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Deletion Category')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='API Request Count')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API Request')),
                ('rate_limit_key', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Rate Limit Identifier')),
                ('tax_name', models.CharField(default='GST', max_length=50, verbose_name='Tax Name')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Tax Number (GSTIN/VAT)')),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='CGST %')),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='SGST %')),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IGST %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='tenants.tenant', verbose_name='Owning Tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configuration',
                'db_table': 'finance_tax_configuration',
            },
        ),
    ]
