# Generated by Django 4.2.7 on 2025-12-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_communication_recipient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.messagethread', verbose_name='Thread'),
        ),
    ]
