# Generated by Django 4.2.7 on 2026-01-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Action URL'),
        ),
    ]
