# Generated by Django 4.2.7 on 2026-01-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ALUMNI', 'Alumni'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred')], db_index=True, default='INCOMPLETE', max_length=20, verbose_name='Status'),
        ),
    ]
