# Generated by Django 4.2.7 on 2025-12-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_tenantconfiguration_square_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='affiliation_number',
            field=models.CharField(blank=True, help_text='Board affiliation number (e.g., CBSE/state board)', max_length=50, null=True, verbose_name='Affiliation Number'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_code',
            field=models.CharField(blank=True, help_text='Official school code', max_length=50, null=True, verbose_name='School Code'),
        ),
    ]
