# Generated by Django 4.2.7 on 2025-12-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_remove_tenant_affiliation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_admission',
            field=models.BooleanField(default=True, verbose_name='Enable Admission Module'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_assignments',
            field=models.BooleanField(default=True, verbose_name='Enable Assignments Module'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_communications',
            field=models.BooleanField(default=True, verbose_name='Enable Communications Module'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_events',
            field=models.BooleanField(default=True, verbose_name='Enable Events/Calendar Module'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_exams',
            field=models.BooleanField(default=True, verbose_name='Enable Exams Module'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_hostel',
            field=models.BooleanField(default=True, verbose_name='Enable Hostel Module'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_hr',
            field=models.BooleanField(default=True, verbose_name='Enable HR Module'),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_transportation',
            field=models.BooleanField(default=True, verbose_name='Enable Transportation Module'),
        ),
    ]
